### ISSUE TITLE
Can't update "Winner Place Distribution Method"

### ISSUE THREAD

**Issue by tmccammon** [geoffhumphrey/brewcompetitiononlineentry#604]
![image](https://cloud.githubusercontent.com/assets/13577083/15247969/3ab4932e-18b3-11e6-8699-b138983b774d.png)

I accidentally set it to 'By Table' while setting up the contest and now that we are done with the first day of judging I am trying to change it to 'By Style'. After clicking set website preferences it say Information Updated but that option does not change.

http://brewmaui.brewcomp.com/

**Comment by geoffhumphrey** [comment]
Hey Thor, try it now. I just updated your installation to 2.1.1 and it should work now.

**Comment by tmccammon** [comment]
Thank you. I see that it is now 'By Style' and I am assuming you made the change after you did the update?

Unfortunately I am still not able to award any more than one 1st, 2nd, or 3rd place per table even if the table has more than one category on it. I am probably doing something wrong in how I setup the tables or flights.

![image](https://cloud.githubusercontent.com/assets/13577083/15255278/ba806b00-18d6-11e6-9ab2-839f5ef29a56.png)

**Comment by geoffhumphrey** [comment]
Yes, that's exactly right. It does have to do with how you set up the tables. You may need to reconfigure your table setup to accommodate the new awards distribution method.

**Comment by tmccammon** [comment]
Ok. Thanks.
